services:
  signaling-server:
    build:
      context: ./server/signaling-server
    image: rift-siege-signaling:dev
    container_name: rift-siege-signaling
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped

  coturn:
    image: docker.io/coturn/coturn:4.6.2
    container_name: coturn-server
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    command:
      - -n
      - --log-file=stdout
      - --external-ip=${TURN_EXTERNAL_IP}
      - --listening-ip=0.0.0.0
      - --min-port=${TURN_MIN_PORT}
      - --max-port=${TURN_MAX_PORT}
      - --user=${TURN_USER}:${TURN_PASSWORD}
      - --lt-cred-mech
      - --realm=${TURN_REALM}
